dist: trusty
sudo: false
language: php
php:
  - '7.1'
install:
   - composer install
script: phpunit -c tests/travis/$DB.phpunit.xml

jobs:
    include:
        stage: test
        env:
           - DB=mariadb
        before_script:
           - mysql -e 'CREATE DATABASE IF NOT EXISTS ppa_test;'
        addons:
            mariadb: 10.1
        